#include "sim.h"
#include "element.h"

const Element element_registry[] = {
	[EMPTY] = { .name = "Empty",
               .color = BLACK,
               .bg_color = BG_BLACK,
               .color_len = sizeof(BLACK) - 1,
               .bg_color_len = sizeof(BG_BLACK) - 1,
               .density = 0,
               .sim_fn = NULL      },

	[WALL] = { .name = "Wall",
	           .color = WHITE,
	           .bg_color = BG_WHITE,
	           .color_len = sizeof(WHITE) - 1,
	           .bg_color_len = sizeof(BG_WHITE) - 1,
	           .density = 255,
	           .sim_fn = NULL      },

	[SAND] = { .name = "Sand",
	           .color = YELLOW,
	           .bg_color = BG_YELLOW,
	           .color_len = sizeof(YELLOW) - 1,
	           .bg_color_len = sizeof(BG_YELLOW) - 1,
	           .density = 100,
	           .sim_fn = sim_sand  },

	[STONE] = { .name = "Stone",
               .color = GRAY,
               .bg_color = BG_GRAY,
               .color_len = sizeof(GRAY) - 1,
               .bg_color_len = sizeof(BG_GRAY) - 1,
               .density = 100,
               .sim_fn = sim_stone },

	[WATER] = { .name = "Water",
               .color = BLUE,
               .bg_color = BG_BLUE,
               .color_len = sizeof(BLUE) - 1,
               .bg_color_len = sizeof(BG_BLUE) - 1,
               .density = 50,
               .sim_fn = sim_water },

	[OIL] = { .name = "Oil",
	           .color = PURPLE,
	           .bg_color = BG_PURPLE,
	           .color_len = sizeof(PURPLE) - 1,
	           .bg_color_len = sizeof(BG_PURPLE) - 1,
	           .density = 10,
	           .sim_fn = sim_oil   },

	[FIRE] = { .name = "Fire",
	           .color = RED,
	           .bg_color = BG_RED,
	           .color_len = sizeof(RED) - 1,
	           .bg_color_len = sizeof(BG_RED) - 1,
	           .density = 1,
	           .sim_fn = sim_fire  },

	[STEAM] = { .name = "Steam",
               .color = WHITE,
               .bg_color = BG_WHITE,
               .color_len = sizeof(WHITE) - 1,
               .bg_color_len = sizeof(BG_WHITE) - 1,
               .density = 1,
               .sim_fn = sim_steam },

	[LAVA] = { .name = "Lava",
	           .color = RED,
	           .bg_color = BG_RED,
	           .color_len = sizeof(RED) - 1,
	           .bg_color_len = sizeof(BG_RED) - 1,
	           .density = 50,
	           .sim_fn = sim_lava  },

	[WOOD] = { .name = "Wood",
	           .color = BROWN,
	           .bg_color = BG_BROWN,
	           .color_len = sizeof(BROWN) - 1,
	           .bg_color_len = sizeof(BG_BROWN) - 1,
	           .density = 100,
	           .sim_fn = sim_wood  },

	[ASH] = { .name = "Ash",
	           .color = LGRAY,
	           .bg_color = BG_LGRAY,
	           .color_len = sizeof(LGRAY) - 1,
	           .bg_color_len = sizeof(BG_LGRAY) - 1,
	           .density = 100,
	           .sim_fn = sim_ash   },

	[EMBER] = { .name = "Ember",
               .color = ORANGE,
               .bg_color = BG_ORANGE,
               .color_len = sizeof(ORANGE) - 1,
               .bg_color_len = sizeof(BG_ORANGE) - 1,
               .density = 100,
               .sim_fn = sim_ember   },

	[GUNPOWDER] = { .name = "Gunpowder",
	                .color = DKOLIVE,
	                .bg_color = BG_DKOLIVE,
	                .color_len = sizeof(DKOLIVE) - 1,
	                .bg_color_len = sizeof(BG_DKOLIVE) - 1,
	                .density = 100,
	                .sim_fn = sim_gunpowder }
};
